### ISSUE TITLE
Add config file 

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#107]
I'd like to think about how we could add a config file so that we could have a better system than just using env variables. Maybe we could also add a "archivy config" command that would open the config file in an editor.

This would be more flexible especially as I add changes related to the login system and permissions that might require more detailed config.

**Comment by Uzay-G** [comment]
@HarshaVardhanJ @srevinsaju @clemux which formats do you think would be best?

**Comment by HarshaVardhanJ** [comment]
YAML? If you're going to have multiple users, YAML is pretty readable.

Something like this :

```yaml
archivy_port: 5000
archivy_data_dir: /archivy/data
archivy_admin_user: "admin"
archivy_admin_hash: "some-hash-value"
archivy_users:
  - name: "User 1"
    user: user1
    hash: "some-hash-1"
  - name: "User 2"
    user: user2
    hash: "some-hash-2"
```
