### ISSUE TITLE
New install escaping home folder

### ISSUE THREAD

**Issue by ygaeon** [archivy/archivy#179]
Have installed archivy in a venv and started it for the first time.

Browsing to the "http://....:5000/?path=" link and clicking the left navigation menu "root"  the url change to "http://....:5000/?path=/".
This allows archivy to load and displays the root file system, browsable.
Seems not right..

```
$ archivy --version
[2021-01-16 14:52:07,780] INFO in __init__: Elasticsearch index already created
Python 3.7.9
Flask 1.1.2
Werkzeug 1.0.1
```
Config:
```
HOST: <internal IP>
INTERNAL_DIR: /home/archivy/.local/share/archivy
PANDOC_HIGHLIGHT_THEME: pygments
PORT: 5000
SEARCH_CONF:
  enabled: 1
  index_name: dataobj
  search_conf:
    mappings:
      properties:
        body:
          analyzer: rebuilt_standard
          type: text
        tags:
          analyzer: rebuilt_standard
          type: text
        title:
          analyzer: rebuilt_standard
          term_vector: with_positions_offsets
          type: text
    settings:
      analysis:
        analyzer:
          rebuilt_standard:
            filter:
            - lowercase
            - kstem
            - trim
            - unique
            stopwords: _english_
            tokenizer: standard
      highlight:
        max_analyzed_offset: 100000000
  url: http://localhost:9200
USER_DIR: /home/archivy
```
